### PR TITLE
[i18n] Update Russian translation

### PR DESCRIPTION
**Pull request by alexls74**

### CODE REVIEW

**Comment by bugwelle** [comment]
Thanks! :smiley: 
Btw, transifex works again and has the latest source strings. If you want, you can translate all strings there :)

**Comment by alexls74** [comment]
Hi!
I'm not sure about numerals (singular, dual, plural) on transifex. Any way, I've updated the translation there.

**Comment by alexls74** [comment]
I've made some corrections on transifex. Could you merge it?

**Comment by bugwelle** [comment]
Done. Please note that windows builds currently fail because http://pkg.mxe.cc/ is offline :)

**Pull request merged**
