### PR TITLE
Can you create a binary package for Ubuntu 17.04 (Release) ?

### PR DESCRIPTION
**Pull request by Paullux**
Hello,

I use Ubuntu 17.04, and i like your software, but if try to install it, i haven't any package in ppa for Zesty (error 404).
If try to install Xenial package, i have an error about qtdeclarative5-dev.

Could you create a package and add an ppa fot Zesty ?

### CODE REVIEW

**Comment by Komet** [comment]
I'm still looking for a maintainer for the ppa. Any pull requests for updating the Ubuntu specific build files are welcome.

**Comment by Paullux** [comment]
how to compil it on ubuntu ?

**Comment by Komet** [comment]
Have a look at http://www.kvibes.de/en/mediaelch/download/
Required packages may need to be adjusted but someone with a little bit of Ubuntu experience has to look into it.

**Comment by Paullux** [comment]
E:The repository 'http://ppa.launchpad.net/kvibes/mediaelch/ubuntu zesty Release' does not have a Release file.

**Comment by Komet** [comment]
Scroll down to compile hints.

**Comment by Paullux** [comment]
finally i install the xenial package : 

i change the ppa to ppa of xenial and i install manually the dependances.
 and all work

**Pull request closed without merging**
