### PR TITLE
Update advancedsettings.xml

### PR DESCRIPTION
**Pull request by Rygle**
Added a bunch of video file extensions and one subtitle extension.

### CODE REVIEW

**Comment by Rygle** [comment]
File formats all supported by VLC and Kodi - probably incomplete, but I added quite a few.
https://forum.kodi.tv/showthread.php?tid=183025
https://forum.kodi.tv/showthread.php?tid=4788
https://kodi.wiki/view/Features_and_supported_formats

**Comment by Rygle** [comment]
Link to issue that relates to this;

https://github.com/Komet/MediaElch/issues/1382

**Comment by Rygle** [comment]
Added *.viv to patch file

Could possibly add some others from this list
https://en.wikipedia.org/wiki/Video_file_format

**Comment by Rygle** [comment]
Would have also added ,*.dfxp to the subtitles section, but I don't think that format is supported in Kodi or VLC. Not 100% sure.

**Review by bugwelle — APPROVED** [review]
Awesome! Thank you very much! :)

Sidenote: There's another list in `AdvancedSettings.cpp` that needs to be kept up in sync. I'll do so.

Thank you very much. :)

**Pull request merged**
