### PR TITLE
add 'EPISODE.DIR&FILENAME'

### PR DESCRIPTION
**Pull request by Stunkymonkey**

### CODE REVIEW

**Review by bugwelle — APPROVED** [review]

**Comment by bugwelle** [comment]
As always: Thanks! 😃

**Comment by Stunkymonkey** [comment]
is a new release date planned? because [my theme](https://github.com/Stunkymonkey/hidaya) is kind of ready for the first release.

**Comment by Stunkymonkey** [comment]
I have opened a issue for the theme #1039

**Comment by bugwelle** [comment]
A new nightly is available as of now. :-)

A new release was planned for Juli/August but that didn't work out. I currently don't have much time to finish the last big change that I want in the next release. I really hope to finish it in November.

**Pull request merged**
