### PR TITLE
[Scrapers] Introduce new TV show scraper interface

### PR DESCRIPTION
**Pull request by bugwelle**
The new scraper is described in `docs/contributing/scraper-interface.md`.

May fix:
 -  #968  
 -  #915
 -  #890
 - #871
 - #861
 - #836
 - #1004

There is still **a lot** to do. Currently only the interface is defined as well as some basic change to make MediaElch compile. Nothing works at the moment! Not even the search.

- [x] Make search work
  - [x] search with different languages
  - [x] Integrate language into UI
- [x] Make TV show scraping work
  - [x] basic details loaded
  - [x] scrape with different languages
  - [x] load *all* show details
- [x] Make episode scraping work
  - [x] single episode scraping works
  - [x] multi episode scraping works
  - [x] episode loading through TV show scraping works
 - [x] Settings overview with language dropdown
 - [x] Custom TV scraper works
 - [x] IMDb scraper
 - [x] Initialization can be repeated
 - [x] "Fill missing episodes" works

### CODE REVIEW

**Comment by bugwelle** [comment]
Language/Scraper drop-down menu in search window works. :)

Screen Shot 2020-05-13 at 14 38 12

**Comment by bugwelle** [comment]
Single episode scraping now works as well.

**Comment by bugwelle** [comment]
Multiepisode scraping works as well. Just some minor issues left. :-)

**Comment by bugwelle** [comment]
Episode scraping through TV show works now as well.
What's left is proper show/episode merging as well as images (that will be the most difficult part I guess).

**Comment by bugwelle** [comment]
New TV scraper settings:

Screen Shot 2020-05-30 at 18 55 07

**Comment by bugwelle** [comment]
New TV search dialog:

Screen Shot 2020-06-01 at 10 23 46

**Comment by bugwelle** [comment]
IMDb search works as well.

**Comment by bugwelle** [comment]
TMDb search and show loading works.

**Comment by bugwelle** [comment]
Open question:

#### How to handle the CustomTvScraper?
The Show search dialog only allows users to show the search results of one scraper. To get the TV scrapers to properly work, we need a user selection for each scraper...
Or we could simply use the first result there is. Need to think about it.

**Comment by bugwelle** [comment]
I want to enable the Custom TV scraper again. But it can't be scraper agnostic. We first need to get the IMDb, TvDb and TmDb ID. The only place where we can do that is TMDb. Or we could limit the scrapers to TvDb and IMDb. I've not decided on that, yet.

**Comment by bugwelle** [comment]
TODO (will update this comment from time to time):

 - [ ] TMDb: Multi-Episode scraper

**Comment by bugwelle** [comment]
Current TMDb TV issue (or feature request): https://www.themoviedb.org/talk/5fa6829f21621d0040f666b3

**Comment by bugwelle** [comment]
## Testing phase 🎉 

### UI
 - [ ] Only fields are selectable that are supported
 - [ ] Only episode order is selectable that are supported
 - [ ] Only load episodes using their ID if the selected show matches the episode's show's ID
        Otherwise we would use the episode's wrong ID.

### Scraping TV Details
- [ ] **TMDB**:
   - [ ] Single Episode Scraping
      - [ ] With ID
      - [ ] Without ID
   - [ ] Multi Episode Scraping
      - [ ] With ID
      - [ ] Without ID
   - [ ] Episode Details
      - [ ] Actors
      - [ ] Certification
      - [ ] Director
      - [ ] FirstAired
      - [ ] Network
      - [ ] Overview
      - [ ] Rating
      - [ ] Thumbnail
      - [ ] Title
      - [ ] Writer
   - [ ] Single Show Scraping
   - [ ] Multi Show Scraping
   - [ ] Show Details
      - [ ] Actors
      - [ ] Banner
      - [ ] Certification
      - [ ] Fanart
      - [ ] FirstAired
      - [ ] Genres
      - [ ] Network
      - [ ] Overview
      - [ ] Poster
      - [ ] Rating
      - [ ] SeasonPoster
      - [ ] Title
      - [ ] Tags
      - [ ] ExtraArts
      - [ ] SeasonBackdrop
      - [ ] SeasonBanner
      - [ ] ExtraFanarts
      - [ ] Thumb
      - [ ] SeasonThumb
      - [ ] Runtime
      - [ ] Status
   - [ ] Update new episodes
   - [ ] Update all episodes
   - [ ] Update all episodes and show
   - [ ] Update new episodes and show
   - [ ] Different episode order

- [ ] **IMDB**:
   - [ ] Single Episode Scraping
      - [ ] With ID
      - [ ] Without ID
   - [ ] Multi Episode Scraping
      - [ ] With ID
      - [ ] Without ID
   - [ ] Episode Details
      - [ ] Actors
      - [ ] Certification
      - [ ] Director
      - [ ] FirstAired
      - [ ] Network
      - [ ] Overview
      - [ ] Rating
      - [ ] Thumbnail
      - [ ] Title
      - [ ] Writer
   - [ ] Single Show Scraping
   - [ ] Multi Show Scraping
   - [ ] Show Details
      - [ ] Actors
      - [ ] Banner
      - [ ] Certification
      - [ ] Fanart
      - [ ] FirstAired
      - [ ] Genres
      - [ ] Network
      - [ ] Overview
      - [ ] Poster
      - [ ] Rating
      - [ ] SeasonPoster
      - [ ] Title
      - [ ] Tags
      - [ ] ExtraArts
      - [ ] SeasonBackdrop
      - [ ] SeasonBanner
      - [ ] ExtraFanarts
      - [ ] Thumb
      - [ ] SeasonThumb
      - [ ] Runtime
      - [ ] Status
   - [ ] Update new episodes
   - [ ] Update all episodes
   - [ ] Update all episodes and show
   - [ ] Update new episodes and show
   - [ ] Different episode order

- [ ] **TheTvDb**:
   - [ ] Single Episode Scraping
      - [ ] With ID
      - [ ] Without ID
   - [ ] Multi Episode Scraping
      - [ ] With ID
      - [ ] Without ID
   - [ ] Episode Details
      - [ ] Actors
      - [ ] Certification
      - [ ] Director
      - [ ] FirstAired
      - [ ] Network
      - [ ] Overview
      - [ ] Rating
      - [ ] Thumbnail
      - [ ] Title
      - [ ] Writer
   - [ ] Single Show Scraping
   - [ ] Multi Show Scraping
   - [ ] Show Details
      - [ ] Actors
      - [ ] Banner
      - [ ] Certification
      - [ ] Fanart
      - [ ] FirstAired
      - [ ] Genres
      - [ ] Network
      - [ ] Overview
      - [ ] Poster
      - [ ] Rating
      - [ ] SeasonPoster
      - [ ] Title
      - [ ] Tags
      - [ ] ExtraArts
      - [ ] SeasonBackdrop
      - [ ] SeasonBanner
      - [ ] ExtraFanarts
      - [ ] Thumb
      - [ ] SeasonThumb
      - [ ] Runtime
      - [ ] Status
   - [ ] Update new episodes
   - [ ] Update all episodes
   - [ ] Update all episodes and show
   - [ ] Update new episodes and show
   - [ ] Different episode order

**Comment by bugwelle** [comment]
Ok, the scrapers all work 🎉 

Here's what's left to do:

 - [ ] The TvShowMultiScrape dialog does not work for multiple shows at the moment
 - [ ] If I scrape multiple episodes with IMDb I get some merge warnings. Probably because the season/episode numbers did not get scraped properly.
 - [ ] Test the CustomTvShowScraper (see above)

These issues will probably not make it into this PR:

 - [ ] Better error reporting if initialisation of scrapers fails
 - [ ] Better progress bars
 - [ ] Load episodes by their IMDb/TheTvDb ID and not by their season/episode number

@txtsd You liked my "Testing" comment. Great to see that you are interested. Would you be interested in testing this PR before I merge it? 😃 

@ticao2 You've always been very helpful and I always appreciate your GitHub issues. So same question: Would you like to test this version before I merge it? 😄

**Comment by ticao2** [comment]
> @ticao2 You've always been very helpful and I always appreciate your GitHub issues. So same question: Would you like to test this version before I merge it? 😄

Yes of course. I use Windows 10 Pro 64, and I always install MediaElch in portable mode.
If possible this way, I install and report the result.
Will you generate a .zip for Windows?

**Comment by bugwelle** [comment]
> Will you generate a .zip for Windows?

Yes. :-)
Just a few issues need to be resolved, first. :-)

**Comment by txtsd** [comment]
@bugwelle Yes! If you give me specific instructions, I can run the tests!

**Comment by bugwelle** [comment]
Thanks! I'll create test executable soon for you. :-)
I've adapted the TvShowMultiScraperDialog and it no longer depends on TheTvDb. I also added a text field with logging information.

**Comment by bugwelle** [comment]
@txtsd What system do you use? I've published binaries for:

 - macOS Big Sur: https://bintray.com/bugwelle/MediaElch/MediaElch-macOS/2.6.7-dev_2020-11-28_11-08_git-tvshowscraper-3cfbe97d?sort=&order=#files
 - Windows: https://bintray.com/bugwelle/MediaElch/MediaElch-win/2.6.7-dev_2020-11-28_11-08_git-tvshowscraper-3cfbe97d?sort=&order=#files

What I'd like to know is whether you experience any crashes or if TV shows aren't properly scraped. Maybe error messages aren't as clear as they should be. Or there may be typos. Have a look at the previous posts in this PR. There are a few screenshots of new features. :-)

**Comment by txtsd** [comment]
@bugwelle I run Arch Linux. I can compile by myself if you point me to a branch.

**Comment by bugwelle** [comment]
Repo and branch are here: https://github.com/bugwelle/MediaElch/tree/tvshowscraper
I don't use Arch but the build instructions for Arch shouldn't be too different: https://mediaelch.github.io/mediaelch-doc/contributing/build/index.html :-)

**Comment by bugwelle** [comment]
@txtsd I'm currently building this branch on different Linux systems. Seems that I forgot a header include. If the build fails, please let me know.

**Comment by txtsd** [comment]
Installed it. I just need to find time to test it now. I'll report back as soon as I can.

**Comment by bugwelle** [comment]
Thank you very much! Take your time. :-)

**Comment by ticao2** [comment]
I was having space problems on the HD. So I'm just answering now. I backed up and solved it.
So, let's go in parts, as Jack The Ripper would say.

I installed in Portable mode.
I configured options as I always do: Brazilian Portuguese language.
In advancedsettings.xml file Debug True option
I have the Dr. House series to test. All Seasons and Episodes.
I put in the folder for scraper only seasons 1 and 2.

When I opened the Scraper interface it looked like this:
Scraper = TMDb TV
Language = English-US> Different from what I chose before.
Found 2 results
In the dropdown, 5 options:

1. Update TV Show only
2. Update TV Show and new Episodes
3. Update TV Show and all Episodes
4. Update new Episodes
5. Update all Episodes

I haven't changed any selection of Details.
I didn't do the Scraper.
Close MediaElch and Copy Debug Log File
[MediaElch_New_2.6.7_Debug_2020-12-01-17-44.log](https://github.com/Komet/MediaElch/files/5625492/MediaElch_New_2.6.7_Debug_2020-12-01-17-44.log)

Would it be necessary to test TMDb and also TVDB and IMDB?
I assume it would be interesting to establish an order.
With seasons 1 and 2 Complete:
1 Open MediaElch
Update TV Show only
Close MediaElch and Copy Debug Log File
2 Open MediaElch
Update TV Show and all Episodes
Close MediaElch and Copy Debug Log File

Add season 3 Complete
3 Open MediaElch
Update TV Show and new Episodes
Close MediaElch and Copy Debug Log File

Add season 4 Partially (10 Episodes)
4 Open MediaElch
Update new Episodes
Close MediaElch and Copy Debug Log File

Am I crazy? Waiting instructions

**Comment by bugwelle** [comment]
Thanks! To answer some questions:

> Scraper = TMDb TV
> Language = English-US> Different from what I chose before.

That happened because TMDb is a new scraper. The language should be saved for each scraper. It is a different one than the movie TMDb scraper. ;-)

The search results for TMDb seems correct: https://www.themoviedb.org/search/tv?query=Dr%20%20House

-----

> Would it be necessary to test TMDb and also TVDB and IMDB?

That would be great. :+1:

I'm only interested in the Debug log if MediaElch should crash.
Otherwise just play around and have a look if MediaElch behaves as you would think. :-)

**Comment by txtsd** [comment]
What settings do I need to change to search with TMDb?
My TV Scraper settings still shows TVDB:
2020-12-02-193354_604x509_scrot
and the only options are TVDB and IMDB.

**Comment by bugwelle** [comment]
Hi,

are you sure that you're on the git branch `tvshowscraper` of my repository? :-)

Because that settings page now looks like this:


Screen Shot 2020-12-02 at 15 11 51
Screen Shot 2020-12-02 at 15 12 18


Regards,
Andre

**Comment by txtsd** [comment]
Woops. Looks like I built master instead. Built the correct branch this time.

**Comment by txtsd** [comment]
These settings don't stick after changing them. They revert to TMDb.:
2020-12-02-204553_763x651_scrot

**Comment by bugwelle** [comment]
@Thanks! Turns out the settings were saved but when displaying them I had introduced a bug... It's now fixed. 😄

**Comment by txtsd** [comment]
I should've mentioned explicitly that in happens in the next tab -Episode Show Details- too.

**Comment by bugwelle** [comment]
That should be fixed as well. Or did I forget to commit all changes?

**Comment by txtsd** [comment]
The first tab is sticking with the last commit, but the second tab isn't.

**Comment by bugwelle** [comment]
Strange. But thanks. I had tested it :/
Will look at it tomorrow. 

Thanks for reporting!

**Comment by bugwelle** [comment]
Yep, forgot to commit `Settings.cpp`. There was a typo in storing the settings. The code needs to be refactored in the future. Copy&Pasting (or rather re-typing) strings everywhere is error-prone...

**Comment by txtsd** [comment]
Ok it sticks now!

**Comment by bugwelle** [comment]
Any major issues? :-)

If not then I'll merge it and will release a new nightly. Then translators can translate all new strings and I'll notify users on the Kodi-forum that they can test it. :-)

**Comment by txtsd** [comment]
I've scraped with all the scrapers, with all the options in the dropdown. No crashes yet so we should be good to go!

**Comment by ticao2** [comment]
Sorry I'm late.

MediaElch NEW

I will change some translations for pt-BR.
Some phrases or words are not in Locale. Is there another way for translation?
The new tab, Scrapers TV, is only for defining language. It does not define the standard, the chosen one, the default. Am I right?
TMDb language list - must be the same for Movies, Concerts and Series.
IMDB has no language option? Just English?

Icon Spacing - I've complained about this before. :-)
Next to the title of the item, in the left column, we have an arrow to open and close the list of Seasons and Episodes.
  - Right Arrow (Closed List) - Invisible
  - Down Arrow (Open List) - Almost Invisible
Update Dropdown options - move up? next to Language? I'm not really sure.

TMDb OK (Season 1 and 2)
TVDB OK (Season 3)
IMDB - very slow (Season 4) English only.

In **Episode > Info** tab we have fields for **TVDB ID** and **IMDB ID**.
Scraper with: 
TMDb = does not add either.
TVDB = adds both
IMDB = only IMDB ID

**Comment by bugwelle** [comment]
> Some phrases or words are not in Locale. Is there another way for translation?

When the PR is merged, I'll update the strings on transifex. Then you'll be able to translate them. :-)
I'll do so for German then.

> The new tab, Scrapers TV, is only for defining language. It does not define the standard font, the chosen one, the default. Am I right?

In the settings dialog,  the only option for all scrapers is the language. I don't get the "standard font". What do you refer to? :-)

> TMDb language list - must be the same for Movies, Concerts and Series.

Should be. But I've looked the their API for the TV scraper more intensive. If the movie/music scraper does not list as many languages, then I have to update them as well.

> IMDB has no language option? Just English?

Correct. To be more precise, I need to update it to "no language available". IMDb has no HTTP header/API option/... to set the language. It is based on the user's IP address... Very annoying, especially for testing the scraper...

> Icon Spacing - I've complained about this before. :-)

Yeah... :-/

----------

Sorry, I'm an in hurry. I'll answer the rest of your points tomorrow. :-)

Thank you all for testing this PR!

**Comment by ticao2** [comment]
> In the settings dialog, the only option for all scrapers is the language. I don't get the "standard font". What do you refer to? :-)

When I reopened the ME to test the IMDB I realized that the scraper selected was TMDb and not the last one that was TVDB.
I suppose that users usually choose a data source they are going to use (IMDB, TVDB or TMDb) and always want to use it.
So, either stay in the memory of Dropdown or somehow select the preferred one somewhere.

> > TMDb language list - must be the same for Movies, Concerts and Series.
> 
> Should be. But I've looked the their API for the TV scraper more intensive. If the movie/music scraper does not list as many languages, then I have to update them as well.

I don't know how many language-COUNTRY are on the list for TMDb here from ME.
But...

**TMDb primary_translations**

https://developers.themoviedb.org/3/configuration/get-primary-translations
Valid for everything: Movies, TV Shows, Concerts (which no longer exists separately) and Profiles of people.
There are **68** on the list but I believe there is one that is not on the list.
**hr-HR** - hr Croatian - HR Croatia
So there are **69**.

And there it is written:
---
Get a list of the officially supported translations on TMDb.
While it's technically possible to add a translation in any one of the languages (186) we have added to TMDb (we don't restrict content), the ones listed in this method are the ones we also support for localizing the website with which means they are what we refer to as the "primary" translations.
---
https://api.themoviedb.org/3/configuration/primary_translations?api_key=THE_KEY

> Sorry, I'm an in hurry. I'll answer the rest of your points tomorrow. :-)

Do not drink too much :-)

**Comment by bugwelle** [comment]
> I suppose that users usually choose a data source they are going to use (IMDB, TVDB or TMDb) and always want to use it.

True. I've added this functionality so that the last used scraper is auto-selected. :-)

> TMDb primary_translations

I'm currently listing 68 languages. I've added `hr-HR`. :-)
I currently do not load the languages from their site. That may come in a future version, though.


> Do not drink too much :-)

Didn't drink anything. 😄 
Just a lot of university stuff.

----------

From your previous post:

> IMDB - very slow (Season 4) 

True.. I'm currently loading each episode one after the other. And their website has always been very slow...

> In Episode > Info tab we have fields for TVDB ID and IMDB ID.
> Scraper with:
> TMDb = does not add either.
> TVDB = adds both
> IMDB = only IMDB ID

Episodes don't have a TMDb ID. But the TMDb episode loader should load all other IDs if and only if you scrape each episode on its own. If you use "update all new episodes" that information is not available, yet.
That's a limitation on their side (in the API). I have to load each episode in a separate request which is annoying. I can't use a "batch request". I still have to update that...

**Comment by bugwelle** [comment]
I've merged this PR. But I have to manually provide new Nightlies because TravisCI does not work for free projects like before anymore.

If you find any other issues, please open a normal GitHub issue. :-)

**Comment by ticao2** [comment]
> That's a limitation on their side (in the API). I have to load each episode in a separate request which is annoying. I can't use a "batch request". I still have to update that...

Perhaps an API Request for TvDB, specifically to obtain only those two IDs, TvDB and IMDB.  
I have no idea if it's simpler or more complex.

**Comment by bugwelle** [comment]
TvDB won't work in the future (starting Jan 2021). :-/

Will work on it.

**Pull request merged**
