### PR TITLE
[TravisCI] Update deployment

### LINKED ISSUE #408: Include ffmpeg and libmediainfo in binary builds

### PR DESCRIPTION
**Pull request by bugwelle**
*Status:* work in progress

This PR fixes #408 

TravisCI now downloads MediaInfo and uses the header files from it instead of downloading the latest master header files. 

### Windows
 - [x] add `ffmpeg`
 - [x] add `MediaInfo.dll`
 - [x] test random screenshot function
 - [x] no missing dependencies (Qml)
 - [x] remove unnecessary Qt libraries (currently all are copied)
 - [x] no file differences between version 2.4.2 and 2.4.3-dev (same folder structure; just a few more image DLLs)

### macOS
 - [x] add `ffmpeg` 
 - [x] add MediaInfo `.dylib`
 - [x] test random screenshot function
 - [x] no missing dependencies (Qml)
 - [x] nice .dmg (see screenshot below)

<div align="center">

</div>

### Linux
*This PR adds some steps to deploying an AppImage but does not fix following issues:*
 - random screenshot function fails
 - no missing dependencies (gstreamer)

### CODE REVIEW

**Comment by bugwelle** [comment]
This PR is nearly ready to be merged. Just some notes.

Example binaries can be found here: https://dl.bintray.com/bugwelle/MediaElch/

### Windows
The windows build should now be ready for production.

 - old ZIP size: ~57MB
 - new ZIP size ~57MB

### macOS
The macOS build should now be ready for production. It now has the same fancy `.dmg` installer as the original version.
@Komet The original version was [signed](https://developer.apple.com/library/content/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html). Should we add this as well?

 - old `.dmg` size: ~33.8MB
 - new `.dmg` size ~42.7MB

### Linux
 - new `.AppImage` size ~45MB

Note: I still need to add gstreamer or fix those warnings.

Full TravisCI log: https://travis-ci.org/bugwelle/MediaElch/jobs/381683938

-------------------

I tried to create an AppImage locally but I failed at some point. @probonopd It seems that I need your help on this. :smiley:  
*(all of this was run locally; the TravisCI build works perfectly)*

Running `./linuxdeployqt appdir/usr/share/applications/MediaElch.desktop -verbose=1 -bundle-non-qt-libs -qmldir=../ui` works except for detecting qml dependencies. I get following error:

```sh
...
^[ERROR: qmlimportscanner not found at "/tmp/.mount_linuxdp06Fmi/usr/bin/qmlimportscanner"
ERROR: Please install it if you want to bundle QML based applications.
```

I don't know why it searches for `qmlimportscanner` in that place. It is definitely installed on my mashine:

```sh
> which qmlimportscanner
> /usr/bin/qmlimportscanner
```

And that's why following modules are missing:

```sh
WARNING:  qrc:/ui/ImageView.qml:1:1: module "QtQuick" is not installed
WARNING:  qrc:/ui/ImageView.qml:2:1: module "QtQml.Models" is not installed
WARNING:  qrc:/ui/ImageView.qml:3:1: module "QtQuick.Controls" is not installed
```

**Comment by probonopd** [comment]
Please run `which qmake` and post the output.

**Comment by bugwelle** [comment]
Thanks for your response. It seems that I messed up my `$PATH` and `linuxdeployqt` got confused with different Qt versions. Everything works now on my local machine, thanks! No `gstreamer` issues or whatsoever. :smiley:  :+1: 

*Steps to reproduce:*

```sh
git clone https://github.com/Komet/MediaElch.git && cd MediaElch
mkdir build && cd $_
qmake ../MediaElch.pro CONFIG+=release PREFIX=/usr
make -j4
export VERSION=2.4
wget --output-document linuxdeployqt https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
chmod a+x ./linuxdeployqt
make INSTALL_ROOT=appdir -j4 install
cp $(which ffmpeg) appdir/usr/bin/
./linuxdeployqt appdir/usr/share/applications/MediaElch.desktop -verbose=2 -bundle-non-qt-libs -qmldir=../ui
./linuxdeployqt appdir/usr/share/applications/MediaElch.desktop -verbose=2 -appimage
chmod +x *.AppImage
```

I will look into the `gstreamer` in the next few days. I think that a package is missing.

**Comment by probonopd** [comment]
Do you want to use the system GStreamer and the system plugins, or do you want to bundle them inside the AppImage?

If you want to bundle GStreamer and its plugins, you may need to look into

-  GST_PLUGIN_PATH: usr/lib/gstreamer-1.0
-  GST_PLUGIN_SYSTEM_PATH: usr/lib/gstreamer-1.0
-  GST_PLUGIN_SCANNER: usr/libexec/gstreamer-1.0/gst-plugin-scanner
 
and possibly set them from a custom `AppRun` bash script. If this turns out to be the case, we may consider to do something in linuxdeployqt.

**Comment by bugwelle** [comment]
Thanks for your reply. Well, at the moment I'm unsure what `gstreamer` plugins we need and how it works. I'm pretty new to `fmpeg`/`gstreamer`/... and still have to read into it.  
I also found a few issues on `linuxdeployqt`'s issue page, so I'm sure we'll find a solution. 😄

**Comment by bugwelle** [comment]
Fixing the AppImage dependencies needs another pull request. Fixing windows and macOS builds is more important at the moment.

The AppImage works on systems that have `libmediainfo` and `ffmpeg` installed. And for systems that do not have them installed, MediaElch simply cannot create random screenshots, detect video runtime and play trailers. The links provided by @probonopd are helpful and I'm sure that we will fix all AppImage issues. I don't know when I'll have time to debug this. Maybe this week, maybe next month.

Packaging all `gstreamer` plugins also results in a 30MB larger binary. 

---------------------

@Komet I'd like to request a review. This PR will make windows and macOS downloads usable. 😄

**Comment by Komet** [comment]
Looks good to me, thank you!

**Comment by probonopd** [comment]
> The AppImage works on systems that have libmediainfo and ffmpeg installed.

Well, it looks like we need to bundle those, too - and their dependencies.

**Pull request merged**
