### PR TITLE
Added other extras to be ignored

### PR DESCRIPTION
**Pull request by sharkbit**
Added -behindthescenes, -deleted, -featurette, -interview, -scene, -short to be ignored when scanning for media files.

### CODE REVIEW

**Comment by sharkbit** [comment]
There might be an easier way to do this like in an array, but a bunch of OR's is pretty easy.

I tend to follow this naming convention:
https://support.plex.tv/articles/200220677-local-media-assets-movies/#toc-3

**Comment by bugwelle** [comment]
For future PRs please run `./scripts/format.sh` before committing changes (if you're on linux or macOS).
The script runs clang-format on the whole repository. Check out https://github.com/Komet/MediaElch/commit/653f9a02980b75e6b1ed691e83bede0c2d65e92e to see how your code was formatted. :smiley: 

We still need to add a batch script for windows, though.

**Comment by sharkbit** [comment]
I use Windows, and was never able to get QT to fully compile the source. So since my changes are usually small I usually just use the web interface in GitHub.   

Thanks, Keep up the great Work!

**Comment by JoaoCarlos78** [comment]
Hi,

Is it possible to change the ignore words for just ignore that word? Ex. as it is it will ignore -scene and -sceneabc, can it be change to just ignore -scene?

Thanks

**Comment by sharkbit** [comment]
Possible, but bond me.  I would suggest changing 'filename.contains' to .endsWith.  Might have to trim off extensions first I dont really know what is included in filename var.

refs:
https://stackoverflow.com/questions/15244911/removing-extension-of-a-file-name-in-qt/15245232
https://het.as.utexas.edu/HET/Software/html/qstring.html#endsWith

**Comment by bugwelle** [comment]
> Hi,
> 
> Is it possible to change the ignore words for just ignore that word? Ex. as it is it will ignore -scene and -sceneabc, can it be change to just ignore -scene?
> 
> Thanks

Sure. What use cases exist for that? :-)
i.e. why don't you use a delimiter such as `-`? :)

**Pull request merged**
