### PR TITLE
Added media flags images

### PR DESCRIPTION
**Pull request by alexls74**

### CODE REVIEW

**Comment by bugwelle** [comment]
Wow, thanks! :+1: 
That are more aspect ratios than I expected. Do you have a list of them? Because I couldn't find one. :)

**Comment by bugwelle** [comment]
Seems you have quite a big movie library. :)

**Comment by alexls74** [comment]
By the way!
`m_videoCodecMappings.insert("v_mpeg4/iso/avc", "h264");` in **AdvancedSettings.cpp**
doesn’t work on macOS any more.

**Comment by bugwelle** [comment]
Compile Error? Or what what exactly happens (or does not happen)?

I'm currently refactoring `StreamDetails` (to avoid strings like `"width"` or `"durationinseconds"`. I can look into it after that. Could open an issue for that?

**Comment by alexls74** [comment]
It's just don’t replace the string.

**Comment by bugwelle** [comment]
Okay, but your `AdvancedSettings.xml` does contain following XML tags?

```xml
  <videoCodecs>
    <map from="v_mpeg4/iso/avc" to="h264" />
  </videoCodecs>
```

**Comment by alexls74** [comment]
AdvancedSettings.xml is working.

**Comment by alexls74** [comment]
Finally it is working!
If `m_videoCodecMappings.insert` is above `m_audioCodecMappings.insert`

```
m_videoCodecMappings.insert("v_mpeg4/iso/avc", "h264");
m_videoCodecMappings.insert("v_mpegh/iso/hevc", "hevc");
m_audioCodecMappings.insert("MPA1L2", "MP2");
m_audioCodecMappings.insert("MPA1L3", "MP3");
```

**Comment by alexls74** [comment]
May I do the next pull request? :)

**Pull request merged**
