### PR TITLE
[CMake] Use modern CMake for external QuaZip usage

### PR DESCRIPTION
**Pull request by bugwelle**
- related #758
 - fix some clang-format issues
 - fix some cmake-format issues

### CODE REVIEW

**Comment by bugwelle** [comment]
@scottfurry FYI, this compiles on Ubuntu but I have some issues using MediaElch which may not even be related to your and my changes. I may not have time to dig in to that this week, though.

**Comment by scottfurry** [comment]
Compiling, running tests, and executing end product were done on my end (self-QA/QC dept.).
Everything seems to run fine on Funtoo (gentoo - derivative) using Qt 5.12.3. Although, FTR, there are some warnings that pop up during compile above looping and assignments.

I have cppcheck and I have a marginal idea of how to use it. ;)

**Comment by bugwelle** [comment]
Hi, just tested older commits before your changes and it seems to be another issue not related to this PR.

> some warnings that pop up during compile above looping and assignments

Yeah, those pop up in release builds. I think most of them are false-positives as the C++11 for each loop should work with Qt containers, so I have no idea why those warnings pop up. :)
I'll most likely just disable them. :)

**Comment by scottfurry** [comment]
@bugwelle - FYI - https://www.embeddeduse.com/2016/05/13/simplifying-loops-with-cpp11/
Discussion of range base for loops and some ideas for usage w/ QT containers.

**Comment by bugwelle** [comment]
Thanks.

> When we move to C++11 in our projects, we should consistently use range-based for instead of index-based loops, iterator-based loops or foreach macros. Based on my experience, we should be able to do this for 95% of the for-loops.

I have replaced most foreach macros with range based for loops. :)
I will look at those warnings again soon. :)

**Pull request merged**
