### PR TITLE
[CSV Export] Add first basic TV show/episode export

### PR DESCRIPTION
**Pull request by bugwelle**
Part of #585

Currently only some fields are supported:

```
TvField::ShowTitle
TvField::ShowImdbid
TvField::ShowTmdbid
TvField::EpisodeSeason
TvField::EpisodeNumber
TvField::EpisodeTitle
TvField::EpisodeOverview
```

Just quickly added some fields. @GarfieldS  What fields would like to have? I'm unsure about adding e.g. the show's overview because having that for each episode (i.e. for each row) is _a lot_ of extra text.

### CODE REVIEW

**Comment by GarfieldS** [comment]
The fields I am interested in are fields that for someone viewing the media can provide opportunities for discovery. 

In that vein: 
- Movie/TV is a default avenue for discovery
- Genre is another one that could allow for discovery of a subset of media withing Movies and/or TV Shows
- Year is another (80s, 90s, 1999, Year I was born, etc)
- Actor - Movies by a specific actor.
- Director - Movies by a specific director. 
- Studio - (less important and yet another avenue to view a subset)

Do I want all of these fields? No. This is just meant to explain the context for the request

**Want**
Year - I want

**Would like to have**
Genre - if possible 
Actor/Director - Would be cool but I understand if it gets to complicated.

**Comment by bugwelle** [comment]
Ok, I've added most TV fields and those that you want. :-)
I'll upload a new Nigthly in about an hour. :-)

**Comment by GarfieldS** [comment]
Thank you very much. Looking forward to how it works in actuality

**Comment by ticao2** [comment]
For me it worked very well. 👍 
Much easier than the "theme" I created.
Automatically creates the two files: Movies and TV Show.
Add to the name YYYY-MM-DD-hh-mm-ss
I missed an **un-check all** option. Nothing important.

**Comment by bugwelle** [comment]
(un)check all and saving the state of the checkboxes throughout re-starts will be added. I wanted to have a basic dialog first. :-)

**Comment by ticao2** [comment]
Yes, I figured that was it.
As for adding {{MOVIE.DIR}}, I don't think I would personally use it.
That's because my other two themes export to HTML table.
And one of the items, a link, is very peculiar. Exporting to .csv and then to HTML will give me more work.
```
<body>
		<ul>
			{{ BEGIN_BLOCK_MOVIE }}
			<tr>
				<td>{{ MOVIE.TITLE }}</td>
				<td>{{ MOVIE.ORIGINAL_TITLE }}</td>
				<td>{{ MOVIE.YEAR }}</td>
				<td>{{ MOVIE.TAGS }}</td>
				<td>{{ MOVIE.GENRES }}</td>
				<td>{{ MOVIE.CERTIFICATION }}</td>
				<td>{{ MOVIE.DIRECTOR }}</td>
				<td>Legenda</td>
				<td><a href="imdbid-{{ MOVIE.IMDB_ID }}">{{ MOVIE.IMDB_ID }}</a></td>
			</tr>
			{{ END_BLOCK_MOVIE }}
		</ul>
  </body>
```

**Pull request merged**
